import jsPDF from "jspdf"

export function generateMediaKit(profile, pitchResult) {
  const doc = new jsPDF()
  const pageWidth = doc.internal.pageSize.getWidth()
  const margin = 20
  let y = 20

  const addLine = (text, fontSize = 12, isBold = false, color = [30, 30, 30]) => {
    doc.setFontSize(fontSize)
    doc.setFont("helvetica", isBold ? "bold" : "normal")
    doc.setTextColor(...color)
    const lines = doc.splitTextToSize(text, pageWidth - margin * 2)
    lines.forEach((line) => {
      if (y > 270) {
        doc.addPage()
        y = 20
      }
      doc.text(line, margin, y)
      y += fontSize * 0.5 + 2
    })
    y += 2
  }

  const addDivider = () => {
    doc.setDrawColor(200, 200, 200)
    doc.line(margin, y, pageWidth - margin, y)
    y += 6
  }

  const addBadge = (text, x, badgeY, bgColor = [37, 99, 235]) => {
    doc.setFillColor(...bgColor)
    doc.roundedRect(x, badgeY - 5, text.length * 2.5 + 10, 8, 2, 2, "F")
    doc.setTextColor(255, 255, 255)
    doc.setFontSize(9)
    doc.setFont("helvetica", "bold")
    doc.text(text, x + 5, badgeY)
    doc.setTextColor(30, 30, 30)
  }

  // ── Header ──
  doc.setFillColor(37, 99, 235)
  doc.rect(0, 0, pageWidth, 40, "F")
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(22)
  doc.setFont("helvetica", "bold")
  doc.text("CreatorPulse Media Kit", margin, 18)
  doc.setFontSize(11)
  doc.setFont("helvetica", "normal")
  doc.text(`Prepared for ${pitchResult.brandName}`, margin, 30)
  doc.setTextColor(30, 30, 30)
  y = 55

  // ── Creator Info ──
  addLine("CREATOR PROFILE", 10, true, [100, 100, 100])
  addLine(profile.name, 20, true)
  addLine(`${profile.platform} · ${profile.niche} Creator`, 12, false, [80, 80, 80])
  y += 4

  addBadge(profile.audienceLocation, margin, y)
  addBadge(`${profile.engagementRate}% Engagement`, margin + 60, y, [5, 150, 105])
  y += 14

  addDivider()

  // ── Stats ──
  addLine("BY THE NUMBERS", 10, true, [100, 100, 100])
  y += 2

  const stats = [
    ["Followers", Number(profile.followers).toLocaleString()],
    ["Engagement Rate", `${profile.engagementRate}%`],
    ["Platform", profile.platform],
    ["Niche", profile.niche],
    ["Posting Frequency", profile.contentFrequency],
    ["Audience Location", profile.audienceLocation],
  ]

  stats.forEach(([label, value]) => {
    doc.setFontSize(10)
    doc.setFont("helvetica", "bold")
    doc.setTextColor(100, 100, 100)
    doc.text(label, margin, y)
    doc.setFont("helvetica", "normal")
    doc.setTextColor(30, 30, 30)
    doc.text(value, margin + 60, y)
    y += 8
  })

  y += 4
  addDivider()

  // ── Fit Score ──
  addLine("BRAND FIT SCORE", 10, true, [100, 100, 100])
  const fitColor =
    pitchResult.fitScore >= 70
      ? [5, 150, 105]
      : pitchResult.fitScore >= 50
      ? [202, 138, 4]
      : [220, 38, 38]
  addLine(`${pitchResult.fitScore}/100 fit with ${pitchResult.brandName}`, 16, true, fitColor)
  addLine(pitchResult.fitReason, 10)
  addDivider()

  // ── Collaboration Ideas ──
  addLine("COLLABORATION IDEAS", 10, true, [100, 100, 100])
  pitchResult.collaborationIdeas?.forEach((idea, i) => {
    addLine(`${i + 1}. ${idea.idea}`, 11, true)
    addLine(`Format: ${idea.format}`, 10, false, [80, 80, 80])
    addLine(idea.whyItWorks, 10)
    y += 2
  })

  addDivider()

  // ── Talking Points ──
  addLine("WHY PARTNER WITH ME", 10, true, [100, 100, 100])
  pitchResult.talkingPoints?.forEach((point) => {
    addLine(`• ${point}`, 10)
  })

  addDivider()

  // ── Footer ──
  doc.setFontSize(9)
  doc.setTextColor(150, 150, 150)
  doc.text(
    `Generated by CreatorPulse · ${new Date().toLocaleDateString()}`,
    margin,
    285
  )

  doc.save(`${profile.name}-MediaKit-${pitchResult.brandName}.pdf`)
}
